alter table if exists event drop constraint if exists fk_admin_id;
alter table if exists event drop constraint if exists fk_participant_id;
alter table if exists event drop constraint if exists fk_contract_id;

drop table if exists "user" cascade;
drop table if exists contract cascade;
drop table if exists event cascade;

create table "user"
(
    user_id bigint generated by default as identity,
    login varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (user_id)
);

create table contract
(
    contract_id bigint generated by default as identity,
    status varchar(255) not null,
    primary key (contract_id)
);

create table event
(
    event_id bigint generated by default as identity,
    admin_id bigint not null,
    contract_id bigint not null,
    price bigint not null,
    participant_id bigint,
    primary key (event_id)
);

alter table if exists event add constraint fk_contract_id foreign key (contract_id) references contract;
alter table if exists event add constraint fk_admin_id foreign key (admin_id) references "user";
alter table if exists event add constraint fk_participant_id foreign key (participant_id) references "user";