alter table if exists "user" drop constraint if exists fk_event_id;
alter table if exists contract drop constraint if exists fk_event_id;

drop table if exists "user" cascade;
drop table if exists contract cascade;
drop table if exists event cascade;

create table "user"
(
    user_id bigint generated by default as identity,
    event_id bigint,
    login varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (user_id)
);

create table contract
(
    event_id bigint not null,
    status varchar(255) not null,
    primary key (event_id)
);

create table event
(
    event_id bigint generated by default as identity,
    name varchar(255) not null,
    price bigint not null,
    primary key (event_id)
);

alter table if exists contract add constraint fk_event_id foreign key (event_id) references event;
alter table if exists "user" add constraint fk_event_id foreign key (event_id) references event;